import { Html, Head, Main, NextScript } from "next/document";
import NextHead from "next/head";

export default function Document() {
  return (
    <Html lang="en">
      <Head />
      <NextHead>
        <title>Ignite 2023 - Firebase</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </NextHead>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
